//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSokovi.ServiceReferenceSokovi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sastojak", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSokovi")]
    [System.SerializableAttribute()]
    public partial class Sastojak : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GustinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ZapreminaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gustina {
            get {
                return this.GustinaField;
            }
            set {
                if ((this.GustinaField.Equals(value) != true)) {
                    this.GustinaField = value;
                    this.RaisePropertyChanged("Gustina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Zapremina {
            get {
                return this.ZapreminaField;
            }
            set {
                if ((this.ZapreminaField.Equals(value) != true)) {
                    this.ZapreminaField = value;
                    this.RaisePropertyChanged("Zapremina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stanje", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSokovi")]
    [System.SerializableAttribute()]
    public partial class Stanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GustinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ZauzeceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gustina {
            get {
                return this.GustinaField;
            }
            set {
                if ((this.GustinaField.Equals(value) != true)) {
                    this.GustinaField = value;
                    this.RaisePropertyChanged("Gustina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Zauzece {
            get {
                return this.ZauzeceField;
            }
            set {
                if ((this.ZauzeceField.Equals(value) != true)) {
                    this.ZauzeceField = value;
                    this.RaisePropertyChanged("Zauzece");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Promena", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSokovi")]
    [System.SerializableAttribute()]
    public partial class Promena : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleSokovi.ServiceReferenceSokovi.Sastojak SastojakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipPromenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ZapreminaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleSokovi.ServiceReferenceSokovi.Sastojak Sastojak {
            get {
                return this.SastojakField;
            }
            set {
                if ((object.ReferenceEquals(this.SastojakField, value) != true)) {
                    this.SastojakField = value;
                    this.RaisePropertyChanged("Sastojak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipPromena {
            get {
                return this.TipPromenaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipPromenaField, value) != true)) {
                    this.TipPromenaField = value;
                    this.RaisePropertyChanged("TipPromena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Zapremina {
            get {
                return this.ZapreminaField;
            }
            set {
                if ((this.ZapreminaField.Equals(value) != true)) {
                    this.ZapreminaField = value;
                    this.RaisePropertyChanged("Zapremina");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSokovi.ISokovi")]
    public interface ISokovi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/dodaj", ReplyAction="http://tempuri.org/ISokovi/dodajResponse")]
        void dodaj(ConsoleSokovi.ServiceReferenceSokovi.Sastojak s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/dodaj", ReplyAction="http://tempuri.org/ISokovi/dodajResponse")]
        System.Threading.Tasks.Task dodajAsync(ConsoleSokovi.ServiceReferenceSokovi.Sastojak s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/flasiraj", ReplyAction="http://tempuri.org/ISokovi/flasirajResponse")]
        void flasiraj(decimal z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/flasiraj", ReplyAction="http://tempuri.org/ISokovi/flasirajResponse")]
        System.Threading.Tasks.Task flasirajAsync(decimal z);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/isprazni", ReplyAction="http://tempuri.org/ISokovi/isprazniResponse")]
        void isprazni();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/isprazni", ReplyAction="http://tempuri.org/ISokovi/isprazniResponse")]
        System.Threading.Tasks.Task isprazniAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/VratiStanje", ReplyAction="http://tempuri.org/ISokovi/VratiStanjeResponse")]
        ConsoleSokovi.ServiceReferenceSokovi.Stanje VratiStanje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/VratiStanje", ReplyAction="http://tempuri.org/ISokovi/VratiStanjeResponse")]
        System.Threading.Tasks.Task<ConsoleSokovi.ServiceReferenceSokovi.Stanje> VratiStanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/Promene", ReplyAction="http://tempuri.org/ISokovi/PromeneResponse")]
        ConsoleSokovi.ServiceReferenceSokovi.Promena[] Promene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISokovi/Promene", ReplyAction="http://tempuri.org/ISokovi/PromeneResponse")]
        System.Threading.Tasks.Task<ConsoleSokovi.ServiceReferenceSokovi.Promena[]> PromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISokoviChannel : ConsoleSokovi.ServiceReferenceSokovi.ISokovi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SokoviClient : System.ServiceModel.ClientBase<ConsoleSokovi.ServiceReferenceSokovi.ISokovi>, ConsoleSokovi.ServiceReferenceSokovi.ISokovi {
        
        public SokoviClient() {
        }
        
        public SokoviClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SokoviClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SokoviClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SokoviClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dodaj(ConsoleSokovi.ServiceReferenceSokovi.Sastojak s) {
            base.Channel.dodaj(s);
        }
        
        public System.Threading.Tasks.Task dodajAsync(ConsoleSokovi.ServiceReferenceSokovi.Sastojak s) {
            return base.Channel.dodajAsync(s);
        }
        
        public void flasiraj(decimal z) {
            base.Channel.flasiraj(z);
        }
        
        public System.Threading.Tasks.Task flasirajAsync(decimal z) {
            return base.Channel.flasirajAsync(z);
        }
        
        public void isprazni() {
            base.Channel.isprazni();
        }
        
        public System.Threading.Tasks.Task isprazniAsync() {
            return base.Channel.isprazniAsync();
        }
        
        public ConsoleSokovi.ServiceReferenceSokovi.Stanje VratiStanje() {
            return base.Channel.VratiStanje();
        }
        
        public System.Threading.Tasks.Task<ConsoleSokovi.ServiceReferenceSokovi.Stanje> VratiStanjeAsync() {
            return base.Channel.VratiStanjeAsync();
        }
        
        public ConsoleSokovi.ServiceReferenceSokovi.Promena[] Promene() {
            return base.Channel.Promene();
        }
        
        public System.Threading.Tasks.Task<ConsoleSokovi.ServiceReferenceSokovi.Promena[]> PromeneAsync() {
            return base.Channel.PromeneAsync();
        }
    }
}
