syntax = "proto3";
import "google/protobuf/empty.proto";

option csharp_namespace = "ServerNamespace";

package korisnik;

service KorisniciService{
	rpc CreateKorisnika(Korisnik) returns(Poruka);
	rpc ReadKorisnika(Identifikator) returns(Korisnik);
	rpc UpdateKorsnika(UpdateTip) returns(Poruka);
	rpc DelteKorisnika(Identifikator) returns(google.protobuf.Empty);
	rpc ReadFromToKorisnika(Opseg) returns(stream Korisnik);
	rpc DeleteStreamKorisnika(stream Identifikator) returns(stream Poruka);
	rpc ReadStreamKorisnika(google.protobuf.Empty) returns(stream Korisnik);
}
message Identifikator{
	int32 id = 1;
}

message Korisnik{
	Identifikator identifikator = 1;
	string imeKorsinika = 2;
	string prezimeKorisnika = 3;
	optional string adresaKorisnika = 4;
	string brTelefona = 5;
}

message Poruka{
	string Tekst = 1;
}

message Opseg{
	Identifikator idFrom = 1;
	Identifikator idTo = 2;
}

message UpdateTip{
	Identifikator id = 1;
	Korisnik korisnik = 2;
}