//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReferenceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTest.IServiceVreme", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IServiceVreme {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVreme/GetDate", ReplyAction="http://tempuri.org/IServiceVreme/GetDateResponse")]
        System.DateTime GetDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVreme/GetDate", ReplyAction="http://tempuri.org/IServiceVreme/GetDateResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVreme/GetBrojPoziva", ReplyAction="http://tempuri.org/IServiceVreme/GetBrojPozivaResponse")]
        int GetBrojPoziva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVreme/GetBrojPoziva", ReplyAction="http://tempuri.org/IServiceVreme/GetBrojPozivaResponse")]
        System.Threading.Tasks.Task<int> GetBrojPozivaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceVremeChannel : WindowsFormsApp1.ServiceReferenceTest.IServiceVreme, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceVremeClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReferenceTest.IServiceVreme>, WindowsFormsApp1.ServiceReferenceTest.IServiceVreme {
        
        public ServiceVremeClient() {
        }
        
        public ServiceVremeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceVremeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVremeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVremeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetDate() {
            return base.Channel.GetDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetDateAsync() {
            return base.Channel.GetDateAsync();
        }
        
        public int GetBrojPoziva() {
            return base.Channel.GetBrojPoziva();
        }
        
        public System.Threading.Tasks.Task<int> GetBrojPozivaAsync() {
            return base.Channel.GetBrojPozivaAsync();
        }
    }
}
