//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rezultat", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Rezultat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RezultatOperacijeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operacija {
            get {
                return this.OperacijaField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacijaField, value) != true)) {
                    this.OperacijaField = value;
                    this.RaisePropertyChanged("Operacija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RezultatOperacije {
            get {
                return this.RezultatOperacijeField;
            }
            set {
                if ((this.RezultatOperacijeField.Equals(value) != true)) {
                    this.RezultatOperacijeField = value;
                    this.RaisePropertyChanged("RezultatOperacije");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IKalkulatorService", CallbackContract=typeof(Client.ServiceReference1.IKalkulatorServiceCallback))]
    public interface IKalkulatorService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulatorService/obrisiRacunanje")]
        void obrisiRacunanje();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulatorService/obrisiRacunanje")]
        System.Threading.Tasks.Task obrisiRacunanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/dodajBroj", ReplyAction="http://tempuri.org/IKalkulatorService/dodajBrojResponse")]
        void dodajBroj(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/dodajBroj", ReplyAction="http://tempuri.org/IKalkulatorService/dodajBrojResponse")]
        System.Threading.Tasks.Task dodajBrojAsync(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/oduzmiBroj", ReplyAction="http://tempuri.org/IKalkulatorService/oduzmiBrojResponse")]
        void oduzmiBroj(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/oduzmiBroj", ReplyAction="http://tempuri.org/IKalkulatorService/oduzmiBrojResponse")]
        System.Threading.Tasks.Task oduzmiBrojAsync(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/pomnoziBrojem", ReplyAction="http://tempuri.org/IKalkulatorService/pomnoziBrojemResponse")]
        void pomnoziBrojem(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/pomnoziBrojem", ReplyAction="http://tempuri.org/IKalkulatorService/pomnoziBrojemResponse")]
        System.Threading.Tasks.Task pomnoziBrojemAsync(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/podeliBrojem", ReplyAction="http://tempuri.org/IKalkulatorService/podeliBrojemResponse")]
        void podeliBrojem(int broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/podeliBrojem", ReplyAction="http://tempuri.org/IKalkulatorService/podeliBrojemResponse")]
        System.Threading.Tasks.Task podeliBrojemAsync(int broj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalkulatorServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulatorService/CallbackObavestiKlijenta")]
        void CallbackObavestiKlijenta(Client.ServiceReference1.Rezultat rez);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalkulatorServiceChannel : Client.ServiceReference1.IKalkulatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KalkulatorServiceClient : System.ServiceModel.DuplexClientBase<Client.ServiceReference1.IKalkulatorService>, Client.ServiceReference1.IKalkulatorService {
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void obrisiRacunanje() {
            base.Channel.obrisiRacunanje();
        }
        
        public System.Threading.Tasks.Task obrisiRacunanjeAsync() {
            return base.Channel.obrisiRacunanjeAsync();
        }
        
        public void dodajBroj(int broj) {
            base.Channel.dodajBroj(broj);
        }
        
        public System.Threading.Tasks.Task dodajBrojAsync(int broj) {
            return base.Channel.dodajBrojAsync(broj);
        }
        
        public void oduzmiBroj(int broj) {
            base.Channel.oduzmiBroj(broj);
        }
        
        public System.Threading.Tasks.Task oduzmiBrojAsync(int broj) {
            return base.Channel.oduzmiBrojAsync(broj);
        }
        
        public void pomnoziBrojem(int broj) {
            base.Channel.pomnoziBrojem(broj);
        }
        
        public System.Threading.Tasks.Task pomnoziBrojemAsync(int broj) {
            return base.Channel.pomnoziBrojemAsync(broj);
        }
        
        public void podeliBrojem(int broj) {
            base.Channel.podeliBrojem(broj);
        }
        
        public System.Threading.Tasks.Task podeliBrojemAsync(int broj) {
            return base.Channel.podeliBrojemAsync(broj);
        }
    }
}
