//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICalculatorService")]
    public interface ICalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/clearState", ReplyAction="http://tempuri.org/ICalculatorService/clearStateResponse")]
        void clearState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/clearState", ReplyAction="http://tempuri.org/ICalculatorService/clearStateResponse")]
        System.Threading.Tasks.Task clearStateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/add", ReplyAction="http://tempuri.org/ICalculatorService/addResponse")]
        void add(float number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/add", ReplyAction="http://tempuri.org/ICalculatorService/addResponse")]
        System.Threading.Tasks.Task addAsync(float number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/subtract", ReplyAction="http://tempuri.org/ICalculatorService/subtractResponse")]
        void subtract(float number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/subtract", ReplyAction="http://tempuri.org/ICalculatorService/subtractResponse")]
        System.Threading.Tasks.Task subtractAsync(float number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/multiply", ReplyAction="http://tempuri.org/ICalculatorService/multiplyResponse")]
        void multiply(float number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/multiply", ReplyAction="http://tempuri.org/ICalculatorService/multiplyResponse")]
        System.Threading.Tasks.Task multiplyAsync(float number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/divide", ReplyAction="http://tempuri.org/ICalculatorService/divideResponse")]
        void divide(float number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculatorService/divide", ReplyAction="http://tempuri.org/ICalculatorService/divideResponse")]
        System.Threading.Tasks.Task divideAsync(float number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceChannel : Client.ServiceReference1.ICalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ICalculatorService>, Client.ServiceReference1.ICalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void clearState() {
            base.Channel.clearState();
        }
        
        public System.Threading.Tasks.Task clearStateAsync() {
            return base.Channel.clearStateAsync();
        }
        
        public void add(float number) {
            base.Channel.add(number);
        }
        
        public System.Threading.Tasks.Task addAsync(float number) {
            return base.Channel.addAsync(number);
        }
        
        public void subtract(float number) {
            base.Channel.subtract(number);
        }
        
        public System.Threading.Tasks.Task subtractAsync(float number) {
            return base.Channel.subtractAsync(number);
        }
        
        public void multiply(float number) {
            base.Channel.multiply(number);
        }
        
        public System.Threading.Tasks.Task multiplyAsync(float number) {
            return base.Channel.multiplyAsync(number);
        }
        
        public void divide(float number) {
            base.Channel.divide(number);
        }
        
        public System.Threading.Tasks.Task divideAsync(float number) {
            return base.Channel.divideAsync(number);
        }
    }
}
