//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.KalkulatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KalkulatorServiceReference.IKalkulatorService", CallbackContract=typeof(Client.KalkulatorServiceReference.IKalkulatorServiceCallback))]
    public interface IKalkulatorService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulatorService/obrisiRacunanje")]
        void obrisiRacunanje();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulatorService/obrisiRacunanje")]
        System.Threading.Tasks.Task obrisiRacunanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/saberi", ReplyAction="http://tempuri.org/IKalkulatorService/saberiResponse")]
        float saberi(float broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/saberi", ReplyAction="http://tempuri.org/IKalkulatorService/saberiResponse")]
        System.Threading.Tasks.Task<float> saberiAsync(float broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/oduzmi", ReplyAction="http://tempuri.org/IKalkulatorService/oduzmiResponse")]
        float oduzmi(float broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/oduzmi", ReplyAction="http://tempuri.org/IKalkulatorService/oduzmiResponse")]
        System.Threading.Tasks.Task<float> oduzmiAsync(float broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/pomnozi", ReplyAction="http://tempuri.org/IKalkulatorService/pomnoziResponse")]
        float pomnozi(float broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/pomnozi", ReplyAction="http://tempuri.org/IKalkulatorService/pomnoziResponse")]
        System.Threading.Tasks.Task<float> pomnoziAsync(float broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/podeli", ReplyAction="http://tempuri.org/IKalkulatorService/podeliResponse")]
        float podeli(float broj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKalkulatorService/podeli", ReplyAction="http://tempuri.org/IKalkulatorService/podeliResponse")]
        System.Threading.Tasks.Task<float> podeliAsync(float broj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalkulatorServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IKalkulatorService/CallbackPrikaziRacunanje")]
        void CallbackPrikaziRacunanje(string rez);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKalkulatorServiceChannel : Client.KalkulatorServiceReference.IKalkulatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KalkulatorServiceClient : System.ServiceModel.DuplexClientBase<Client.KalkulatorServiceReference.IKalkulatorService>, Client.KalkulatorServiceReference.IKalkulatorService {
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public KalkulatorServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void obrisiRacunanje() {
            base.Channel.obrisiRacunanje();
        }
        
        public System.Threading.Tasks.Task obrisiRacunanjeAsync() {
            return base.Channel.obrisiRacunanjeAsync();
        }
        
        public float saberi(float broj) {
            return base.Channel.saberi(broj);
        }
        
        public System.Threading.Tasks.Task<float> saberiAsync(float broj) {
            return base.Channel.saberiAsync(broj);
        }
        
        public float oduzmi(float broj) {
            return base.Channel.oduzmi(broj);
        }
        
        public System.Threading.Tasks.Task<float> oduzmiAsync(float broj) {
            return base.Channel.oduzmiAsync(broj);
        }
        
        public float pomnozi(float broj) {
            return base.Channel.pomnozi(broj);
        }
        
        public System.Threading.Tasks.Task<float> pomnoziAsync(float broj) {
            return base.Channel.pomnoziAsync(broj);
        }
        
        public float podeli(float broj) {
            return base.Channel.podeli(broj);
        }
        
        public System.Threading.Tasks.Task<float> podeliAsync(float broj) {
            return base.Channel.podeliAsync(broj);
        }
    }
}
